Internal Server Error: /auth/logout
Traceback (most recent call last):
  File "C:\Users\dpsha\AppData\Roaming\Python\Python312\site-packages\django\urls\base.py", line 71, in reverse
    extra, resolver = resolver.namespace_dict[ns]
                      ~~~~~~~~~~~~~~~~~~~~~~~^^^^
KeyError: 'redirection'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dpsha\AppData\Roaming\Python\Python312\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dpsha\AppData\Roaming\Python\Python312\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dpsha\AppData\Roaming\Python\Python312\site-packages\django_ratelimit\decorators.py", line 27, in _wrapped
    return fn(request, *args, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Any-Time-Event\auth1\views.py", line 358, in logout
    resposnse=HttpResponseRedirect(reverse('redirection:index'))
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dpsha\AppData\Roaming\Python\Python312\site-packages\django\urls\base.py", line 82, in reverse
    raise NoReverseMatch("%s is not a registered namespace" % key)
django.urls.exceptions.NoReverseMatch: 'redirection' is not a registered namespace
"GET /auth/logout HTTP/1.1" 500 87354
